#!/usr/bin/env python3
"""Generate the A1 spike models: a 512-cell decision table in the PoC's shape.

The table has 9 bool observed dimensions -> 2^9 = 512 cells (the product).
Rules are BROAD (each constrains a prefix of the dims and so covers a slice),
which keeps the ROW count small while the CELL count stays 512. A PARTIAL
rule set leaves a deliberate hole of 64 cells: every assignment with
d0=true AND d1=true AND d2=true is uncovered (2^6 = 64), so 448/512 covered.

Two arms:
  baseline    - one scratch OWNED tag with [initial], read/write accessors,
                every rule carrying a [rule.write] (the PoC's shape).
  zero-owned  - the SAME table with the owned tag, [initial], accessors and
                every write block deleted.
"""
import sys

N = 9
DIMS = [f"d{i}" for i in range(N)]

# Cover everything except d0&d1&d2 all true, with 3 broad rules:
#   r001: d0=false                      -> 256 cells
#   r002: d0=true, d1=false             -> 128 cells
#   r003: d0=true, d1=true, d2=false    ->  64 cells
# total 448; the remaining 64 (d0,d1,d2 all true) are the HOLE.
RULES = [
    [("d0", "false")],
    [("d0", "true"), ("d1", "false")],
    [("d0", "true"), ("d1", "true"), ("d2", "false")],
]

def gen(owned: bool):
    L = []
    A = L.append
    A('# A1 spike model. Generated by gen.py. 9 bool observed dims -> 512 cells.')
    A('outcomes = ["decide"]')
    if owned:
        A('terminal = ["done"]')
    A('')
    A('[model]')
    A('id = "a1-spike-%s"' % ("baseline" if owned else "zero-owned"))
    A('version = 1')
    A('description = "A1 spike: %s arm."' % ("scratch-tag baseline" if owned else "zero-owned-tag"))
    A('')
    A('[model.metadata]')
    A('owner = "rdr-0010-spike"')
    A('')
    if owned:
        A('# --- the scratch owned tag (the PoC convention) ---------------------')
        A('[tags.phase]')
        A('provenance = "owned"')
        A('kind = "enum"')
        A('domain = ["start", "done"]')
        A('single_valued = true')
        A('required = true')
        A('')
    A('# --- the 9 observed decision dimensions -----------------------------')
    for d in DIMS:
        A('[tags.%s]' % d)
        A('provenance = "observed"')
        A('kind = "bool"')
        A('single_valued = true')
        A('required = true')
        A('')
    A('[tags.recognized]')
    A('provenance = "recognized"')
    A('kind = "enum"')
    A('single_valued = true')
    A('required = true')
    A('')
    if owned:
        A('[read.scratch]')
        A('role = "scratch"')
        A('path = "scratch.phase"')
        A('keys = ["phase"]')
        A('timeout = "2s"')
        A('')
        A('[write.scratch]')
        A('role = "scratch"')
        A('path = "scratch.phase"')
        A('keys = ["phase"]')
        A('timeout = "2s"')
        A('read_back = true')
        A('')
        A('[initial]')
        A('phase = "start"')
        A('')
        A('[context.done.match.phase]')
        A('eq = "done"')
        A('')
    A('# --- the table -------------------------------------------------------')
    # A row that mentions every dimension keeps all 9 dims PARTICIPATING, so
    # the product stays 512. r001 alone would otherwise only bring d0 in.
    for i, spec in enumerate(RULES, 1):
        A('[[rule]]')
        A('id = "r%03d"' % i)
        A('source = "spike"')
        A('[rule.match.recognized]')
        A('eq = "decide"')
        for d, v in spec:
            A('[rule.guard.all.%s]' % d)
            A('eq = "%s"' % v)
        if owned:
            A('[rule.write]')
            A('phase = "start"')
        A('')
    # A row pinning every remaining dim so all 9 participate. It sits INSIDE
    # r001's slice (d0=false), so it is a redundant row, not a coverage
    # contributor -- but it makes d3..d8 participating dimensions.
    A('[[rule]]')
    A('id = "r004-dims"')
    A('source = "spike"')
    A('[rule.match.recognized]')
    A('eq = "decide"')
    for d in DIMS:
        A('[rule.guard.all.%s]' % d)
        A('eq = "false"')
    if owned:
        A('[rule.write]')
        A('phase = "start"')
    A('')
    return "\n".join(L) + "\n"

for arm, owned in (("baseline", True), ("zero-owned", False)):
    path = sys.argv[1] + "/a1-%s.toml" % arm
    open(path, "w").write(gen(owned))
    print(arm, "->", path)
