package cli

// The `docs` verb: the command tree describes itself into files.
//
// intrastate's reference material — the flag grammar, the finding
// taxonomy, the refusal vocabulary, the exit contract — already lives in
// the binary, derived from the same constants the wire is emitted from
// (see help_all.go). Restating any of it in hand-written markdown
// creates a second description that rots the moment a code is renamed.
// So the markdown is GENERATED from the live command tree instead, and
// `make docs` plus a CI staleness gate keep the committed copy honest.
//
// Shape follows the prior art in the peer Go CLIs (helm's `helm docs`,
// goreleaser's `man`): a HIDDEN subcommand inside the shipped binary,
// rather than a separate `cmd/gen-docs` program. A second main package
// would have to reconstruct the command tree — and a generator that
// builds its own tree can silently describe a different CLI than the one
// that ships. Reaching cmd.Root() from inside the binary cannot.
//
// It is hidden because it addresses maintainers, not callers: it does
// not belong in the command list a user reads to learn the tool. It is
// still fully documented under `--help` for whoever runs it.
//
// One rule governs everything emitted here: NOTHING may vary between two
// builds of the same source. In particular the ldflags-stamped version
// never appears in generated output — it would dirty the committed files
// on every release build and turn the staleness gate into noise.

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/cwensel/intrastate/internal/cli/clierr"
	"github.com/cwensel/intrastate/internal/cli/respond"
	"github.com/spf13/cobra"
)

// generatedBanner marks every generated file. It carries the command
// that reproduces the file, so a reader who wants to change it is told
// what to run instead of editing a file their edit would not survive.
const generatedBanner = `<!-- AUTO-GENERATED by ` + "`make docs`" + `. DO NOT EDIT.
     The source is the command tree in internal/cli; edit the command's
     Long text or its withExtendedHelp body, then run ` + "`make docs`" + `. -->`

// docsPayload is the verb's success payload: the files written, relative
// to the output directory, in the order written.
type docsPayload struct {
	Dir   string   `json:"dir"`
	Files []string `json:"files"`
}

func newDocsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:    "docs",
		Short:  "Generate the reference documentation from this command tree",
		Hidden: true,
		Long: `Generate the reference documentation from this command tree.

The command tree is the source of truth: this writes docs/cli-reference.md
and llms.txt from the same help bodies ` + "`--help-all`" + ` prints, so the
committed markdown cannot describe a CLI this binary does not implement.

Run it through ` + "`make docs`" + `; ` + "`make check`" + ` fails when the
committed copies are stale.`,
		SilenceErrors: true,
		SilenceUsage:  true,
		Args:          cobra.NoArgs,
		RunE:          runDocs,
	}
	cmd.Flags().String("dir", ".", "repository root to write the generated files under")
	withExtendedHelp(cmd, docsExtendedDesc)
	return cmd
}

const docsExtendedDesc = `Files written, both relative to --dir:

  docs/cli-reference.md   the full command reference — every command's
                          terse body, usage, flags, and extended help.
  llms.txt                the agent-oriented index, per the llms.txt
                          convention: what the tool is, the command
                          surface, and where the full reference lives.

Determinism is a contract, not a nicety. The staleness gate in
` + "`make check`" + ` regenerates these files and fails if the result
differs from what is committed, so anything that varies between two
builds of the same source would fail the build at random. That is why
the ldflags-stamped version appears in neither file.

To change what these files say, change what the COMMAND says — its Long
text, or its withExtendedHelp body — and regenerate. Editing the output
directly does not survive the next run.`

func runDocs(cmd *cobra.Command, _ []string) error {
	if ce := respond.ValidateMode(cmd); ce != nil {
		return respond.Fail(cmd, ce)
	}
	dir, _ := cmd.Flags().GetString("dir")
	root := cmd.Root()

	files := []struct {
		path   string
		render func(*strings.Builder, *cobra.Command)
	}{
		{filepath.Join("docs", "cli-reference.md"), writeCLIReference},
		{"llms.txt", writeLLMsTxt},
	}

	written := make([]string, 0, len(files))
	for _, f := range files {
		full := filepath.Join(dir, f.path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return respond.Fail(cmd, &clierr.CLIError{
				Code:    "docs-write-failed",
				Param:   "dir",
				Message: "cannot create the directory for " + f.path,
				Detail:  err.Error(),
				Group:   clierr.GroupUserEnv,
				Cause:   err,
			})
		}
		var buf strings.Builder
		f.render(&buf, root)
		if err := os.WriteFile(full, []byte(buf.String()), 0o644); err != nil {
			return respond.Fail(cmd, &clierr.CLIError{
				Code:    "docs-write-failed",
				Param:   "dir",
				Message: "cannot write " + f.path,
				Detail:  err.Error(),
				Group:   clierr.GroupUserEnv,
				Cause:   err,
			})
		}
		written = append(written, f.path)
	}

	return respond.OK(cmd, respond.Success{
		Data: docsPayload{Dir: dir, Files: written},
	})
}

// line, linef, and raw write to a strings.Builder, whose Write is
// documented never to return an error. Going through them rather than
// fmt.Fprintln keeps the renderers free of 70 unchecked-error sites that
// could not fail and could not be meaningfully handled if they did.
// line writes each string then a newline; linef formats first; raw
// writes without the newline.
//
// They take a *strings.Builder rather than an io.Writer because
// Builder.Write is documented never to return an error. That keeps the
// renderers free of ~70 unchecked-error sites that could not fail and
// could not be handled if they did — and it is a real constraint, not a
// convenience: a renderer that could fail mid-document would need an
// error path through every call, for a writer that has none.
func line(w *strings.Builder, parts ...string) {
	for _, p := range parts {
		w.WriteString(p)
	}
	w.WriteByte('\n')
}

func raw(w *strings.Builder, s string) {
	w.WriteString(s)
}

// writeCLIReference renders the whole tree: for each command, its terse
// body, its usage block, and its extended help. It is the file form of
// `intrastate --help-all`, and it is built by walking the SAME tree that
// command walks — there is no second description to keep in step.
func writeCLIReference(w *strings.Builder, root *cobra.Command) {
	line(w, generatedBanner)
	line(w)
	line(w, "# intrastate CLI reference")
	line(w)
	line(w, "Every command, its flags, and its extended reference.")
	line(w, "The same content is available from the binary itself:")
	line(w)
	line(w, "```sh")
	line(w, "intrastate --help-all           # this whole document")
	line(w, "intrastate <command> --help-all # one command's section")
	line(w, "```")

	walkCommandTree(root, func(c *cobra.Command) {
		if c.Hidden {
			return
		}
		line(w)
		line(w, "## "+c.CommandPath())
		line(w)
		if c.Short != "" {
			line(w, c.Short)
			line(w)
		}
		if body := strings.TrimRight(c.Long, " \t\r\n"); body != "" && body != c.Short {
			line(w, "```")
			line(w, body)
			line(w, "```")
			line(w)
		}
		line(w, "```")
		raw(w, usageWithoutVersion(c))
		line(w, "```")
		if ext := extendedHelpFor(c); ext != "" {
			line(w)
			line(w, "```")
			line(w, ext)
			line(w, "```")
		}
	})
}

// writeLLMsTxt renders llms.txt per the convention: an H1, a blockquote
// summary, then annotated links. The command surface is enumerated from
// the live tree so a new verb appears here without anyone remembering to
// add it.
//
// It points an agent at the binary first. A file is a snapshot; the
// binary is the build actually installed, and `--help-all --as=json` is
// the machine-readable form of the same content.
func writeLLMsTxt(w *strings.Builder, root *cobra.Command) {
	line(w, "# intrastate")
	line(w)
	line(w, "> A Go CLI that makes workflow state transitions explicit, reviewable,")
	line(w, "> and deterministic. A flow is authored once as a transition model — a")
	line(w, "> TOML document of tags, rules, guards, and writes — and callers")
	line(w, "> navigate it by asking the CLI rather than reimplementing the flow in")
	line(w, "> a skill, script, or agent. Given the same model, state, tags, and")
	line(w, "> recognized outcome, the answer is the same every time: one legal")
	line(w, "> plan, or one typed refusal.")
	line(w)
	line(w, "The binary is authoritative and self-describing. Prefer asking it over")
	line(w, "reading any file here — a file is a snapshot, the binary is the build")
	line(w, "you actually have:")
	line(w)
	line(w, "```sh")
	line(w, "intrastate --help-all      # every command's full reference")
	line(w, "intrastate <cmd> --help-all")
	line(w, "intrastate <cmd> --as=json # one terminal JSON envelope per run")
	line(w, "```")
	line(w)
	line(w, "If `intrastate` is not on PATH:")
	line(w)
	line(w, "```sh")
	line(w, "go install github.com/cwensel/intrastate/cmd/intrastate@latest")
	line(w, "```")
	line(w)

	line(w, "## Commands")
	line(w)
	walkCommandTree(root, func(c *cobra.Command) {
		if c.Hidden || c.Parent() == nil {
			return
		}
		path := c.CommandPath()
		line(w, "- [`"+path+"`](docs/cli-reference.md#"+anchorFor(path)+"): "+c.Short)
	})
	line(w)

	line(w, "## Docs")
	line(w)
	line(w, "- [CLI reference](docs/cli-reference.md): every command, flag, and")
	line(w, "  extended body — generated from the command tree.")
	line(w, "- [Model authoring](docs/model-authoring.md): how to author a")
	line(w, "  transition model in TOML — the model class, a decision table's")
	line(w, "  cells, and the escape row. Not derivable from the CLI surface.")
	line(w, "- [Output contract](docs/cli-output-contract.md): worked JSON")
	line(w, "  payloads and the rationale behind the envelope shape.")
	line(w, "- [Examples](docs/examples.md): the models, drawn — state machines")
	line(w, "  and decision tables from this repo and from a real consumer.")
	line(w, "- [README](README.md): what it is, install, and a first invocation.")
	line(w)

	line(w, "## Examples")
	line(w)
	line(w, "- [pricing-decision-table.toml](models/examples/pricing-decision-table.toml):")
	line(w, "  a stateless decision table, a proved 2x2 of tier x region with no")
	line(w, "  gap, overlap, or escape row.")
	line(w, "- [release-grammar.toml](models/examples/release-grammar.toml): the")
	line(w, "  full grammar surface in one model — every tag kind, guard operator,")
	line(w, "  and accessor construct the docs snippets are copied from.")
	line(w, "- [review-state-machine.toml](models/examples/review-state-machine.toml):")
	line(w, "  a stateful review flow, draft to approved or rejected, with escape")
	line(w, "  rows closing the uncovered cases.")
	line(w, "- [routing-decision-table.toml](models/examples/routing-decision-table.toml):")
	line(w, "  a decision table with a partitioned emit domain, routing severity x")
	line(w, "  owner into named dispositions.")
	line(w, "- [rdr.toml](models/rdr.toml): the model this repo's own")
	line(w, "  decision-record workflow runs on — the RDR lifecycle, Stage 1")
	line(w, "  through Stage 8.")
	line(w)

	line(w, "## Optional")
	line(w)
	line(w, "- [Decision records](docs/rdr/README.md): the locked design decisions")
	line(w, "  behind the contracts above. History and rationale; the code is the")
	line(w, "  source of truth.")
	line(w, "- [Joint decision records](docs/jdr/README.md): decisions two or more")
	line(w, "  sibling RDRs jointly own, hoisted to one normative home instead of")
	line(w, "  restated in each.")
	line(w, "- [CONTRIBUTING](CONTRIBUTING.md): layout, the contract every verb")
	line(w, "  follows, and the build targets.")
}

// anchorFor derives a GitHub-style markdown anchor from a command path
// (e.g. "intrastate flow next"): lowercased, with spaces replaced by
// hyphens. It exists so the Commands section can link into
// docs/cli-reference.md's "## <path>" headings without hand-computing
// the anchor at each call site.
func anchorFor(path string) string {
	return strings.ReplaceAll(strings.ToLower(path), " ", "-")
}

// usageWithoutVersion is cmd.UsageString with the ldflags-stamped
// `--version` line dropped.
//
// Cobra renders that flag's help as `version for intrastate` with no
// stamp in it, so today the string is already stable — but the stamp
// sits one template change away from the usage block, and a generated
// file that changes per build would fail the staleness gate on release
// builds only. Dropping the line keeps the gate honest by construction
// rather than by luck.
func usageWithoutVersion(c *cobra.Command) string {
	var kept []string
	for line := range strings.SplitSeq(c.UsageString(), "\n") {
		if strings.Contains(line, "--version") {
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}
